### ISSUE TITLE
Unable to stop a -t ICMP Ping

### ISSUE THREAD

**Issue by Zakk220** [adevries17/NetPTN#16]
After having a -t ICMP ping run for a few seconds the stop button no longer works. Seems like the application starts to go unresponsive and has to be killed off due to the number of pings being sent.

**Comment by Zakk220** [comment]
Seems to be a bit better after the new release.

**Comment by adevries17** [comment]
Fixed with commit d2645bf640e7f34532c08f144c1e0e10858fe2a8
