### ISSUE TITLE
Add latency timer output to the traceroutes section

### ISSUE THREAD

**Issue by crousoe** [adevries17/NetPTN#19]
Would be nice to have the latency timer(s) built in to the traceroute piece, similar to the way command prompt works.  Being able to see any unusual time disparities between the incrementing hops would help with troubleshooting.  See image for example:

![tracert example](https://github.com/adevries17/NetPTN/assets/124317895/f96b4437-2a56-4e6f-94c7-3aed081a7665)

**Comment by adevries17** [comment]
@crousoe For the new version, do you still want a couple different timers for each hop? Right now v1 only checks once per hop. I am planning on adding latency as part of the output, need to know how many requests to send to each hop. The more there are, the slower the traceroute will get.

**Comment by adevries17** [comment]
Added in 376b654ef65fc87441f98f17cb1f334c3197af18
